version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    restart: 'unless-stopped'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: typeorm-template
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  mongo:
    image: mongo
    restart: 'unless-stopped'
    expose:
      - '27017'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongoose-template
