version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    restart: 'unless-stopped'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: typeorm-template
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  mongo:
    image: mongo
    restart: 'unless-stopped'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  # Mongo Web Tool
  mongo-express:
    image: mongo-express
    restart: 'unless-stopped'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
