version: '3.7'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: 'unless-stopped'
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:
# https://github.com/jenkinsci/docker/blob/master/README.md
# 젠킨스 접속해서 /var/jenkins_home/secrets initialAdminPassword 입력 후, 플러그인 설치
# 계정 등록
